name: Docker versioned
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
        with:
          strip_v: true
      - uses: actions/checkout@v3
      - uses: docker/login-action@v1.12.0
        with:
          username: dprohe
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2.8.0
        with:
          push: true
          tags: |
            dprohe/sdynpy:${{steps.tag.outputs.tag}}
            dprohe/sdynpy:latest
      - run: sleep 500s
  test:
    needs: build
    runs-on: ubuntu-22.04
    container: dprohe/sdynpy
    steps:
      - run: python -m pytest --verbose src/sdynpy
